### DISCUSSION TITLE
HOW TO CHANGE TO DEFAULT COLOR SCHEME

### DISCUSSION THREAD

**Discussion by TOXIC6163** [Eugeny/tabby#5330] [Q&A]
how to change tabby color scheme to default ?

**Comment by ChJus** [comment]
## Method 1
The default color scheme for Tabby is the OceanicMaterial theme (according to the default config file [method 2]), so you can set it to that by applying the theme.

## Method 2
Take a look at the "Config file" section of the settings. There is a button "Show defaults" that shows the default configurations for Tabby. Scroll down to `terminal`, and there should be a section called `colorScheme`. You can replace your current color scheme (with the default attached below) from there. Don't forget to click "Save and apply" and also set "Terminal background" to "from color scheme" (in the Appearance tab).

```
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    selection: null
    cursor: '#FFCC00'
    cursorAccent: null
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
```
