### DISCUSSION TITLE
change tab color

### DISCUSSION THREAD

**Discussion by lovesharepc** [Eugeny/tabby#6109] [Q&A] [answered]
does any way change tab color 
there color is too close ,  very difficult to distinguish which tab is active
![2022-04-07_00-19](https://user-images.githubusercontent.com/1570732/162021205-7f07ac9d-f82e-4ed3-a9b8-88c5f3076e8b.png)

**Comment by AvinsWang** [comment]
Same to me, It's hard to distinguish which Tab is active

**Reply by Otpvondoiats** [reply]
very hard...

**Reply by yydog** [reply]
![image](https://user-images.githubusercontent.com/31811831/178148472-fec4d38a-439d-4146-b598-fe44eb9945da.png)

**Reply by yydog** [reply]
![image](https://user-images.githubusercontent.com/31811831/178148495-eff64333-78ac-43d3-9bb9-ef13c061a877.png)

**Comment by Gaibhne** [comment, marked as answer]
I found this via Google and since the given answers didn't make me happy, I came up with the following CSS, which will make the selected tab brighter no matter which theme you use - if you use a light theme, you probably want to rewrite this to make the tab darker instead.

Go to **Settings** / **Appearance** / **Custom CSS** (which you'll find at the very bottom) and paste the following CSS (and beware of people telling you to paste things without at least basic understanding of what you're doing):

```css
#cdk-drop-list-0 > tab-header.ng-tns-c127-0.fully-draggable.ng-trigger.ng-trigger-animateTab.ng-star-inserted.active {
  background-image: linear-gradient(rgb(255 255 255/15%) 0 0);
  background-blend-mode: lighten;
}
```

What this does is overlay the selected tab with a completely white background, set to a low alpha (15%, which you can adjust of course) and blend it in a way that only allows it to lighten the color of the tab.

Edit: looks like this (with the *Solarized Dark* theme):

![image](https://user-images.githubusercontent.com/24731712/226929166-022cb7cb-caf6-44d1-ad66-0b123c0473d1.png)
