### DISCUSSION TITLE
Light Theme for Tabby

### DISCUSSION THREAD

**Discussion by ponchofiesta** [Eugeny/tabby#7115] [General]
As there is no light theme available I tried to modify the CSS a bit. If someone wants to use it too, feel free to do so.

This "theme" only makes the tab bar light.

![image](https://user-images.githubusercontent.com/12248938/189601934-48b253cf-50d7-4450-8c31-ba97a0257bbe.png)

**Setup**

Used color scheme in the screenshot is _ayu_light_.

- Open **Settings**
- Go to **Appearance**
- Scroll down to **Custom CSS** and paste the CSS:

```css

/* Light theme (tab bar) */
app-root {
    border: 0 !important;
}
tab-header,
.tab-bar>.btn-group button,
app-root>.content .tab-bar>.tabs tab-header button {
    color: black !important;
}
tab-header,
window-controls {
    background: rgb(205, 205, 205) !important;
    border: 1px solid rgb(205, 205, 205) !important;
    z-index: 0;
}
tab-header:after,
tab-header:last-child:before {
    content: "";
    background: rgb(114, 114, 114);
    position: absolute;
    bottom: 15%;
    height: 70%;
    width: 1px;
}
tab-header:after {
    left: 0;
}
tab-header:last-child:before {
    right: 0;
}
tab-header:hover {
    background: rgb(220, 220, 220) !important;
}
tab-header.active {
    background: rgb(247, 247, 247) !important;
    border: 1px solid rgb(247, 247, 247) !important;
    box-shadow: rgba(60, 64, 67, 0.3) 0px 1px 2px 0px, rgba(60, 64, 67, 0.15) 0px 2px 6px 2px;
    clip-path: inset(0px -6px 0px -6px);
    z-index: 1;
}
tab-header:first-child:after,
tab-header.active:after,
tab-header.active + tab-header:after,
tab-header.active:before {
    display: none;
}
app-root>.content .tab-bar>.tabs tab-header button:hover,
.tab-bar>.drag-space,
.tab-bar>.btn-group {
    background: rgb(207, 207, 207) !important;
}
.tab-bar>.drag-space,
.tab-bar>.btn-group {
    margin: 0 !important;
    border: 0 !important;
}
tab-header .activity-indicator {
    background: #4fadff !important;
}
app-root .tab-bar window-controls svg {
    fill: black;
}
app-root .tab-bar window-controls button:hover {
    background: rgb(184, 184, 184);
}
app-root .tab-bar window-controls button.btn-close:hover {
    background: rgb(232, 17, 35);
}
app-root .tab-bar window-controls button.btn-close:hover svg {
    fill: white;
}
```

Maybe there are other and better ways. I didn't find any so I did it this way.

**Issues**
- A thin black border on the right.
