### DISCUSSION TITLE
How to remove bottom and right border ?

### DISCUSSION THREAD

**Discussion by samos667** [Eugeny/tabby#7351] [Q&A]
I have successfully remove left and top border with this:
![image](https://user-images.githubusercontent.com/50653464/197164282-2d457ef2-0c71-4e91-a926-5921e2b064c1.png)

But he doesn't remove right and bottom border:
![image](https://user-images.githubusercontent.com/50653464/197164883-d61e2c4b-228b-401a-b773-64a1feaa9bac.png)

Any solution for this ?

**Comment by Eugeny** [comment]
You can't remove these without resizing the terminal, because terminal cells have fixed size

**Reply by samos667** [reply]
You know how can I rezize terminal for SSH connection ?

**Reply by Eugeny** [reply]
I meant resizing the window with your mouse. There's just no way to fit e.g. 80 of 20px wide cells into 170px wide space without borders

**Comment by jockrow** [comment]
Hi, this is the completed css to remove all borders:
```css
 tab-body div.content{
         padding: 0 0 0 0 !important;
         margin: 0 0 0 0 !important;
         width: 101%;
         height: 105%;
 }
 ```

But you will sacrifice the visible scroll, even in the Settings Tab, although I prefer that :)
