### ISSUE TITLE
Broken on v1.0.216; Failed to convert napi value String into rust type `u32` on ssh connection

### ISSUE THREAD

**Issue by AwesomeDog** [Eugeny/tabby#10135]
**Describe the problem**:
[A clear and concise description of what the bug is.]

when ssh to a connection, it will show " Failed to convert napi value String into rust type `u32`"

**To Reproduce**:
[Steps to reproduce the behavior]

probably when u define a ssh port on ssh connection, and connect it, it will broken.

v1.0.215  ok    
v1.0.216 not ok

**Comment by Eugeny** [comment]
Please paste the config chunk corresponding to that connection here or send it to inbox@null.page if you prefer

**Comment by AwesomeDog** [comment]
> Please paste the config chunk corresponding to that connection here or send it to [inbox@null.page](mailto:inbox@null.page) if you prefer

**Comment by AwesomeDog** [comment]
> Please paste the config chunk corresponding to that connection here or send it to [inbox@null.page](mailto:inbox@null.page) if you prefer

```
profiles:
  - name: my-vm
    options:
      host: 127.0.0.1
      port: '2200'
      keepaliveInterval: '30'
      keepaliveCountMax: '3'
```
the problem resides in `keepaliveInterval` and `keepaliveCountMax` , if the two lines were deleted, the error vanished.
