### ISSUE TITLE
Vibrancy + Opacity doesn't work macOS Sequoia 15.3.2

### ISSUE THREAD

**Issue by Misery7100** [Eugeny/tabby#10416]
Version: 1.0.223
Platform: macOS arm64 24.3.0
Plugins: docker
Frontend: xterm-webgl

<img width="1822" alt="Image" src="https://github.com/user-attachments/assets/0edad1e9-60a3-476a-98c2-9ca2252684c5" />

Checked couple of resolved issues - seems like the problem is still there

**Comment by Misery7100** [comment]
There is some workaround with custom css btw:

```css
app-root.vibrant {
    background: rgba(var(--bs-dark-rgb), 0.2);
}
```

By default it's 0.65 and adding `opacity` (I guess) break `rgba`.
