### ISSUE TITLE
terminus locking up

### ISSUE THREAD

**Issue by xenoterracide** [Eugeny/tabby#3193]
ok, this is going to start as a garbage report, I'm not certain how best to collect details and hoping for advice. Twice now on OSX Terminus has completely locked up and I had to kill it. Both times same command was (had?) been run `./gradlew build --stacktrace` and I believe I was scrolling the results.

Terminus: `Version 1.0.121 (1.0.121)`
```
> uname -a                                                          # ~
Darwin Calebs-MBP 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
```

can you advise how I might collect better details of what's happening? I suppose I could run strace (does that even work on mac?)

ok, just reproduced it again, dtruss output looks useless... steps were

1. `./gradlew build --stacktrace`
2. let it finish
3. scroll up
4. double click to highlight a stacktrace line

now terminus is not responding. 

this doesn't happen every time, so I'm not sure what's different yet.

here's my config file

```yml
terminal:
  searchOptions: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: 'rgba(38, 50, 56, 1)'
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - 'rgba(255, 255, 255, 0.2)'
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  ligatures: true
  hideTabIndex: true
  environment: {}
  alwaysUseWorkingDirectory: true
  profile: zsh
  autoOpen: false
  bracketedPaste: true
  copyOnSelect: true
hotkeys:
  profile: {}
  shell: {}
  toggle-window: []
serial: {}
ssh: {}
appearance:
  dock: 'off'
  opacity: 1
enableWelcomeTab: false
pluginBlacklist:
  - ssh
  - serial
```

I also have the clickable links plugin `1.0.2` installed.
