### ISSUE TITLE
pwsh.exe (v7) doesnt launch while powershell.exe (v5) with custom commands

### ISSUE THREAD

**Issue by PipeItToDevNull** [Eugeny/tabby#4024]
```
  profiles:
    - name: pwsh
      shell: default
      sessionOptions:
        command: pwsh.exe
        args:
          - '-nologo'
          - '-noprofile'
          - '-noexit'
          - '-command ". C:\Users\user\profile.ps1"'
        env: {}
    - name: PowerShell-Personal
      sessionOptions:
        command: powershell.exe
        args:
          - '-nologo'
          - '-noprofile'
          - '-noexit'
          - . C:\Users\user\profile.ps1
```

powershell launches just fine using the above profile, but `pwsh.exe` does not. I can run `pwsh.exe` in CMD as `pwsh.exe -nologo -noprofile -noexit -command ". C:\Users\user\profile.ps1"` and it launches fine though. 

The terminal closes too quickly for me to see the error message. If there is a way to see that I think it would help me to get to the bottom of this. I think terminus could be launching `pwsh.exe` in a unique way that causes this break.
