### ISSUE TITLE
why login scripts in config can't surrounded by double quotes 

### ISSUE THREAD

**Issue by windzhu0514** [Eugeny/tabby#4115]
After filling in the login script ，config file is show below ;
```
scripts:
        - expect: Opt>
          send: p \r
        - expect: Opt>
          send: 172.24.88.78 \r
        - expect: ']$'
          send: cd /data/sessionSvr_GSPublicWeb \r
        - expect: ']$'
          send: ls
```

it's can not work normall，so i cant login the server
