### ISSUE TITLE
The Fluent Mode does not look like the same as Windows Terminal or system's default

### ISSUE THREAD

**Issue by AndlollipopDE** [Eugeny/tabby#4305]
I am running Tabby on Windows 11, I notice that the Fluent mode of Tabby does not look like the fluent effect presented in the Windows Terminal or the system's default. I am wondering that is it a bug or it is just the way it is

**Comment by microhobby** [comment]
@AndlollipopDE  what I have noticed is that the transparency of Windows 11 depends a lot on the accent color. On electron apps this accent color does not apply "automagically", it's have to be set on the background color together with the alpha.  

Check the second video here https://github.com/Eugeny/tabby/pull/5902
I'm using:

```css
app-root.vibrant {
         background: rgba(0, 0, 0, 0.5) !important;
}

tab-body {
        background: transparent !important;
}
```

On Windows terminal if you ran `ctrl+shift` + `mouse scroll` you can set the transparency (which kind of drops the accent color and makes the background more like "transparent glass"). But from the API that tabby uses today it doesn't seem possible to set this.
