### ISSUE TITLE
Cannot add new profiles

### ISSUE THREAD

**Issue by BernardoPilarz** [Eugeny/tabby#4330]
I'm trying to add new profiles (SSH Connections, to be specific), but 99% of the times the procedure will fail.
When I click on "Save" the profile pop-up dissappears but the profile has not been added to the list.

**Comment by BernardoPilarz** [comment]
Possible cause: the application is not updating some fields until you click to remove the focus from that field (i.e. the profile 'Name'). Might refuse to insert the profile if some fields are missing.

**Comment by Eugeny** [comment]
Could you please record a screencast? You can mail it to me at e@ajenti.org if there's sensitive info in it.

**Comment by BernardoPilarz** [comment]
> Could you please record a screencast? You can mail it to me at [e@ajenti.org](mailto:e@ajenti.org) if there's sensitive info in it.

I've just sent you an email with a short screencast of the issue.

**Comment by kylhuk** [comment]
Same issue here, yet can't really reproduce it. Sometimes the profiles get stored, sometimes not.

**Comment by nevotheless** [comment]
Same issue here. I tried installing the newest version on 2 devices today and wasn't able to save new connections.

**Comment by zaxtyson** [comment]
Same issue with OpenSUSE, and it seems the disable Build-in button disappeared.

It lists all the possible shells and tty serial ports on my system, and the build-in list probably has dozens of items.

![](https://i.imgur.com/HKwmlPe.png)

**Comment by Eugeny** [comment]
Thanks @BernardoPilarz, could you please test the latest nightly build?

**Comment by matheus1776** [comment]
> Thanks @BernardoPilarz, could you please test the latest nightly build?

I tested it here, and it's the same. 
                                                                                                                                                                
Version: 1.0.151-nightly.0
Platform: win32 10.0.19042
Plugins: none

**Comment by matheus1776** [comment]
> > Thanks @BernardoPilarz, could you please test the latest nightly build?
> 
> Version: 1.0.151-nightly.0
> Platform: win32 10.0.19042
> Plugins: none

>Before I test the nightly I was using the latest release, and it was doing the same thing there, it kind of "inserts" the profile, it even appears for very few milliseconds the tab of the new profile but disappears very quickly.

**Comment by rincage** [comment]
Have this issue on one computer but not the other. Both running same version of Windows.

**Comment by BernardoPilarz** [comment]
> Thanks @BernardoPilarz, could you please test the latest nightly build?

Hello, sorry - I've just read your message, but I can see others have tried the latest build and the issue persists.

**Comment by nevotheless** [comment]
G'day.
I just tested the new release 151 and unfortunately the issue persists on my end.

**Comment by Eugeny** [comment]
@nevotheless could you try this build? https://github.com/Eugeny/tabby/actions/runs/1100787299

**Comment by nevotheless** [comment]
I'm trying in this very moment to download the artifacts. But i either get 
![image](https://user-images.githubusercontent.com/779797/128360502-4500dc80-ae5a-4e0d-8bfc-7c481bc5eaa2.png)
from github or a download that probably will never finish as it seems. :/

**Comment by fkramos** [comment]
When using r149 everything was fine.  Updated to r151 and now i can't create profiles.  

Developer Tools Console log, may help: 

core.js:6456 ERROR Error: Uncaught (in promise): Error: EPERM: operation not permitted, rename 'C:\Users\Fabio.Ramos\AppData\Roaming\tabby\config.yaml.new' -> 'C:\Users\Fabio.Ramos\AppData\Roaming\tabby\config.yaml'
Error: EPERM: operation not permitted, rename 'C:\Users\Fabio.Ramos\AppData\Roaming\tabby\config.yaml.new' -> 'C:\Users\Fabio.Ramos\AppData\Roaming\tabby\config.yaml'
    at resolvePromise (zone.js:1213)
    at zone.js:1120
    at rejected (C:\Users\Fabio.Ramos\AppData\Local\Programs\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:8767)
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28666)
    at ZoneDelegate.invoke (zone.js:371)
    at Zone.run (zone.js:134)
    at zone.js:1276
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28653)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)

**Comment by Eugeny** [comment]
@fkramos could you please try this nightly build in case the downloads are working again? (https://github.com/Eugeny/tabby/actions/runs/1100787299)

I've narrowed it down to [antivirus software blocking the just-written config for scanning](https://github.com/npm/npm/issues/12059#issuecomment-269826951) - see if disabling yours has any effect

**Comment by fkramos** [comment]
> @fkramos could you please try this nightly build in case the downloads are working again? (https://github.com/Eugeny/tabby/actions/runs/1100787299)
> 

Tested the nitghtly build and could not reproduce the bug.  Created several profiles with success. 

> I've narrowed it down to [antivirus software blocking the just-written config for scanning](https://github.com/npm/npm/issues/12059#issuecomment-269826951) - see if disabling yours has any effect

Tried disabling antivirus (Windows Defender)  and beside that put Tabby folder for exclusion.  Tested with r151, and I couldn't create new profiles, the bug was still there. 

- x - 
- 
Other thing that I tested (don't know if it could help you),  but I tried to install r151 both for User Only and System Wide, and both of the them didn't work.

**Comment by Eugeny** [comment]
Thanks @fkramos :+1: if others can confirm that the fix works, I'll cut a release

**Comment by nevotheless** [comment]
I just tested it on my pc@home and at work on some devices and it looks good to me 👍🏽 Works as intended now.

**Comment by ljford7** [comment]
I had the bug as well and the nighty version fixed it for me as well.

Thanks!

**Comment by robpomeroy** [comment]
@Eugeny - possible regression with 1.0.156 unfortunately. This is a fresh install (today) on a Win10 VM. Cloning an existing SSH profile or creating a new one both fail. Error thrown in DevTools:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'profileProvider' of undefined
TypeError: Cannot read property 'profileProvider' of undefined
    at ProfilesSettingsTabComponent.<anonymous> (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:14343)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:5894)
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28666)
    at ZoneDelegate.invoke (zone.js:371)
    at Zone.run (zone.js:134)
    at zone.js:1276
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28653)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)
    at ZoneTask.invokeTask [as invoke] (zone.js:491)
    at invokeTask (zone.js:1600)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1626)
    at HTMLButtonElement.sentryWrapped (helpers.js:72)
    at resolvePromise (zone.js:1213)
    at zone.js:1120
    at rejected (C:\Program Files\Tabby\resources\builtin-plugins\tabby-settings\dist\index.js:5895)
    at ZoneDelegate.invoke (zone.js:372)
    at Object.onInvoke (core.js:28666)
    at ZoneDelegate.invoke (zone.js:371)
    at Zone.run (zone.js:134)
    at zone.js:1276
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28653)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at drainMicroTaskQueue (zone.js:582)
    at ZoneTask.invokeTask [as invoke] (zone.js:491)
    at invokeTask (zone.js:1600)
    at HTMLButtonElement.globalZoneAwareCallback (zone.js:1626)
    at HTMLButtonElement.sentryWrapped (helpers.js:72)
```

**Comment by Eugeny** [comment]
I haven't been able to reproduce it so far. If possible, please post your config file or send it to me privately at e@ajenti.org

**Comment by robpomeroy** [comment]
@Eugeny Okay. I rolled forward to .156 again and the problem came back. Apologies, I won't have time today to examine the diffs. There's nothing particularly sensitive in my config:

```
version: 3
profiles:
  - type: ssh
    name: IFS3
    icon: fas fa-desktop
    options:
      host: 192.168.175.101
      user: rob.pomeroy
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      auth: publicKey
      privateKeys:
        - file://C:\Users\Rob\.ssh\the_key
      forwardedPorts: []
      scripts: []
    weight: -1
    id: ssh:custom:IFS3:822dce38-7818-4488-be9f-84e78f0d8d63
  - type: ssh
    name: Ansible01
    icon: fas fa-desktop
    options:
      host: 192.168.175.102
      user: rob
      algorithms: {}
      privateKeys:
        - file://C:\Users\Rob\.ssh\the_key
      auth: publicKey
    weight: -1
    id: ssh:custom:Ansible01-copy:11df7bfe-9f98-47c9-8ecb-3c55ad070102
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  telnet-profile-selector: []
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - Ctrl-Shift-N
  new-tab:
    - Ctrl-Shift-T
  profile: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-T
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-E
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-T
  ssh-profile-selector:
    - - Alt-S
  profile-selectors: {}
terminal:
  searchOptions: {}
  colorScheme:
    name: Dark Pastel
    foreground: '#ffffff'
    background: '#000000'
    cursor: '#bbbbbb'
    colors:
      - '#000000'
      - '#ff5555'
      - '#55ff55'
      - '#ffff55'
      - '#5555ff'
      - '#ff55ff'
      - '#55ffff'
      - '#bbbbbb'
      - '#555555'
      - '#ff5555'
      - '#55ff55'
      - '#ffff55'
      - '#5555ff'
      - '#ff55ff'
      - '#55ffff'
      - '#ffffff'
  customColorSchemes: []
  hideTabIndex: true
  hideCloseButton: true
ssh: {}
configSync:
  parts: {}
appearance:
  vibrancy: false
  flexTabs: true
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults: {}
```

I have reverted back to .155 and once more, profile cloning & creation works.

**Comment by robpomeroy** [comment]
@Eugeny Okay. I rolled forward to .156 again and the problem came back. Apologies, I won't have time today to examine the diffs. There's nothing particularly sensitive in my config:

```
version: 3
profiles:
  - type: ssh
    name: IFS3
    icon: fas fa-desktop
    options:
      host: 192.168.175.101
      user: rob.pomeroy
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      auth: publicKey
      privateKeys:
        - file://C:\Users\Rob\.ssh\the_key
      forwardedPorts: []
      scripts: []
    weight: -1
    id: ssh:custom:IFS3:822dce38-7818-4488-be9f-84e78f0d8d63
  - type: ssh
    name: Ansible01
    icon: fas fa-desktop
    options:
      host: 192.168.175.102
      user: rob
      algorithms: {}
      privateKeys:
        - file://C:\Users\Rob\.ssh\the_key
      auth: publicKey
    weight: -1
    id: ssh:custom:Ansible01-copy:11df7bfe-9f98-47c9-8ecb-3c55ad070102
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - Ctrl-Shift-C
  paste:
    - Ctrl-Shift-V
  select-all:
    - Ctrl-Shift-A
  clear: []
  zoom-in:
    - Ctrl-=
    - Ctrl-Shift-=
  zoom-out:
    - Ctrl--
    - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  telnet-profile-selector: []
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - Ctrl-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - Ctrl-Shift-N
  new-tab:
    - Ctrl-Shift-T
  profile: {}
  toggle-fullscreen:
    - F11
    - Alt-Enter
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-T
  toggle-last-tab: []
  rename-tab:
    - Ctrl-Shift-R
  next-tab:
    - Ctrl-Shift-Right
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Left
    - Ctrl-Shift-Tab
  move-tab-left:
    - Ctrl-Shift-PageUp
  move-tab-right:
    - Ctrl-Shift-PageDown
  rearrange-panes:
    - Ctrl-Shift
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - Ctrl-Shift-E
  split-bottom:
    - Ctrl-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-previous:
    - Ctrl-Alt-[
  pane-nav-next:
    - Ctrl-Alt-]
  pane-maximize:
    - Ctrl-Alt-Enter
  close-pane: []
  switch-profile:
    - Ctrl-Alt-T
  profile-selector:
    - Ctrl-Shift-T
  ssh-profile-selector:
    - - Alt-S
  profile-selectors: {}
terminal:
  searchOptions: {}
  colorScheme:
    name: Dark Pastel
    foreground: '#ffffff'
    background: '#000000'
    cursor: '#bbbbbb'
    colors:
      - '#000000'
      - '#ff5555'
      - '#55ff55'
      - '#ffff55'
      - '#5555ff'
      - '#ff55ff'
      - '#55ffff'
      - '#bbbbbb'
      - '#555555'
      - '#ff5555'
      - '#55ff55'
      - '#ffff55'
      - '#5555ff'
      - '#ff55ff'
      - '#55ffff'
      - '#ffffff'
  customColorSchemes: []
  hideTabIndex: true
  hideCloseButton: true
ssh: {}
configSync:
  parts: {}
appearance:
  vibrancy: false
  flexTabs: true
enableWelcomeTab: false
pluginBlacklist: []
profileDefaults: {}
```

I have reverted back to .155 and once more, profile cloning & creation works.
