### ISSUE TITLE
What should I do to open a new tab with my home directory?

### ISSUE THREAD

**Issue by minoritea** [Eugeny/tabby#4415]
I want to open a new tab in my home directory, but it always opens in the last directory I opened.
No option was found to enable this behavior.

What should I do to solve this?

Here is my current configuration:
```
terminal:
  searchOptions: {}
  environment: {}
  workingDirectory: /Users/minori_tokuda
  colorScheme:
    name: Afterglow
    foreground: '#d0d0d0'
    background: '#212121'
    cursor: '#d0d0d0'
    colors:
      - '#151515'
      - '#ac4142'
      - '#7e8e50'
      - '#e5b567'
      - '#6c99bb'
      - '#9f4e85'
      - '#7dd6cf'
      - '#d0d0d0'
      - '#505050'
      - '#ac4142'
      - '#7e8e50'
      - '#e5b567'
      - '#6c99bb'
      - '#9f4e85'
      - '#7dd6cf'
      - '#f5f5f5'
  customShell: /usr/local/bin/bash
  alwaysUseWorkingDirectory: true
  customColorSchemes: []
  ligatures: true
  background: colorScheme
  fallbackFont: Apple Color Emoji
  profile: local:custom:profile1:11b7e4bb-c2a3-47f5-a68b-0984b013d078
hotkeys:
  toggle-window: []
  shell: {}
  profile: {}
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  telnet-profile-selector: []
  restart-telnet-session: []
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - ⌘-N
  new-tab:
    - ⌘-T
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - ⌘-Shift
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
serial: {}
ssh: {}
appearance: {}
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - ssh
version: 3
profiles:
  - type: local
    icon: fas fa-terminal
    options:
      command: /usr/local/bin/bash
      env: {}
      cwd: /home/minori_tokuda
      args: []
    name: bash(my)
    id: local:custom:profile1:11b7e4bb-c2a3-47f5-a68b-0984b013d078
configSync:
  parts: {}
recoverTabs: false
```
