### ISSUE TITLE
Multi-line text paste formatting problem

### ISSUE THREAD

**Issue by ykgw-quliang** [Eugeny/tabby#4576]
Version: 1.0.156
Platform: Windows x64 10.0.19043
Plugins: none
Frontend: xterm
-----------------------------------------------
The contents of my yaml file
```yaml
server:
  port: 8888
  path: /path
name: 
  first: tian
  second: song
```
-----------------------------------------------
vi test.yaml

![image](https://user-images.githubusercontent.com/66979744/132783406-429dfe7f-e397-4803-a506-664046cb6d32.png)
