### ISSUE TITLE
Reduce width of the Pane separator

### ISSUE THREAD

**Issue by sabz90** [Eugeny/tabby#4616]
![image](https://user-images.githubusercontent.com/16514261/133784785-b3632572-13e7-400b-826a-e8caf9327d34.png)
Is it possible to reduce this width of the pane separator?

**Comment by Eugeny** [comment]
Yes - you can customize these via custom CSS (Settings -> Appearance), e.g.:

```css
split-tab-spanner.v {
	height: 5px !important;
}

split-tab-spanner.h {
	width: 5px !important;
}
```
