### ISSUE TITLE
Install from tar.gz for Linux has no built in profiles and unable to launch any terminal tabs

### ISSUE THREAD

**Issue by TraceyC77** [Eugeny/tabby#4654]
Version: 1.0.158
Platform: Linux x64 5.14.7-198.current
Plugins: theme-gruvbox, relaxed-theme, clickable-links
Frontend: xterm

Distribution: Solus

# Install has no built in profiles and is unable to open any terminal tabs

I've also installed Tabby on a Windows 10 desktop. It has the expected built in profiles, and is able to create new profiles and open new tabs as expected. I installed from tarball for Linux since there is no package in the Solus repo.

I'm happy to provide any additional information that might help troubleshoot and resolve this issue.

## Installation
I had downloaded the tarball from github and untarred it in a subdirectory under ~/bin/
Running it with `./tabby` in that directory opened Tabby as expected
Since I didn't see any install docs or README file, it doesn't appear I needed to do anything else to complete the install from source.

## Issues
* Clicking "New Terminal" on the main screen does nothing
* The "new terminal" and "new tab with profile" buttons do nothing.
* In Settings - Profiles there are no profiles listed under "Built-in" as there are on Windows
Clicking "New profile" brings up a dialog that wants me to "Select a base profile to use as a template" but since there are none, this dialog doesn't do anything. I'm unable to create a profile. 
* Under Settings - Config file, clicking "Show config file" briefly brings up a Dolphin file manager window to ~/.config/tabby which immediately closes. I verified that directory does exist:

```
❰user❙~/bin/tabby-1.0.158-linux❱✔≻ ll ~/.config/ |rg tabby
drwx------ 11 user user 4.0K Sep 25 15:12 tabby/
❰user❙~/bin/tabby-1.0.158-linux❱✔≻ ll ~/.config/tabby
total 100K
drwx------ 11 user user 4.0K Sep 25 15:12  ./
drwxrwxr-x 88 user user  12K Sep 25 15:15  ../
drwx------  3 user user 4.0K Sep 25 15:07  blob_storage/
drwx------  4 user user 4.0K Sep 25 14:30 'Code Cache'/
drwx------  2 user user 4.0K Sep 25 14:30 'Crash Reports'/
drwx------  2 user user 4.0K Sep 25 14:30  Dictionaries/
drwx------  2 user user 4.0K Sep 25 14:30  GPUCache/
drwx------  3 user user 4.0K Sep 25 14:30 'Local Storage'/
drwxr-xr-x  3 user user 4.0K Sep 25 14:40  plugins/
drwxr-xr-x  2 user user 4.0K Sep 25 14:30  sentry/
drwx------  2 user user 4.0K Sep 25 14:40 'Session Storage'/
-rw-r--r--  1 user user  207 Sep 25 15:12  config.yaml
-rw-r--r--  1 user user  207 Sep 25 15:12  config.yaml.backup
-rw-------  1 user user  20K Sep 25 14:39  Cookies
-rw-------  1 user user    0 Sep 25 14:39  Cookies-journal
-rw-r--r--  1 user user  769 Sep 25 15:07  log.txt
-rw-------  1 user user  729 Sep 25 15:07 'Network Persistent State'
-rw-------  1 user user   57 Sep 25 14:30  Preferences
lrwxrwxrwx  1 user user   20 Sep 25 15:07  SingletonCookie -> 17926332019254103631
lrwxrwxrwx  1 user user   11 Sep 25 15:07  SingletonLock -> selar-16959
lrwxrwxrwx  1 user user   37 Sep 25 15:07  SS -> /tmp/.org.chromium.Chromium.XMmXcA/SS=
-rw-------  1 user user  369 Sep 25 14:48  TransportSecurity
-rw-r--r--  1 user user  107 Sep 25 15:07  window.json
```

The config file contents show in the "Config file" view are much more sparse on Linux than on Windows
### Linux config

```
version: 3
profiles: []
hotkeys:
  toggle-window:
    - Ctrl-Space
terminal:
  searchOptions: {}
ssh: {}
configSync:
  parts: {}
appearance: {}
pluginBlacklist: []
enableWelcomeTab: false
clickableLinks: {}
```

### Windows config
```
version: 3
profiles: []
hotkeys:
  toggle-window:
    - Ctrl-Space
terminal:
  searchOptions: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    selection: null
    cursor: '#FFCC00'
    cursorAccent: null
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  fontSize: 13
  ligatures: true
ssh: {}
configSync:
  parts: {}
appearance: {}
enableWelcomeTab: false
pluginBlacklist: []

```
## Expected behavior:
The default profiles are provided in the tarball and displayed in the UI.
If any extra steps are necessary to complete the install from tarball are documented in an easy to find place.
