### ISSUE TITLE
Meta+Shift+C not sent to tmux

### ISSUE THREAD

**Issue by anoriqq** [Eugeny/tabby#4815]
Hi

Unable to send Meta(Alt)+Shift+C to tmux. In fact, it seems that Meta+c is being sent.
Also, even if it is not C-key, shift will be ignored for other keys as will.

I'm expecting Meta+Shift+C to be sent to tmux.

▼ .tmux.conf
```.tmux.conf
# working
bind -n M-c new-window -c "#{pane_current_path}"

# not working. M-c new-window works instead
bind -n M-C new-session
```

Thank you

---

Tabby Ver: Alpha 1.0.159
Windows 10 Pro 21H1
WSL Ver 2 (Kernel Ver 5.10.60.1 / Ubuntu-20.04)

<details>
<summary>config file</summary>

```yml
terminal:
  searchOptions: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(0, 0, 0, 0)
    selection: null
    cursor: '#FFCC00'
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  font: Cica Regular
  hideCloseButton: true
  fallbackFont: Consolas Regular
  profile: local:custom:WSL-Ubuntu-18.04-copy:6be06603-6eb1-4a77-af27-60f83a502072
  bell: visual
  copyOnSelect: true
  workingDirectory: //wsl$/Ubuntu-20.04/home/anoriqq
  fontSize: 36
  ligatures: true
  scrollOnInput: false
  bracketedPaste: true
  rightClick: menu
  autoOpen: false
  customColorSchemes:
    - name: Material
      foreground: '#eceff1'
      background: rgba(0, 0, 0, 0)
      selection: null
      cursor: '#FFCC00'
      colors:
        - '#000000'
        - '#D62341'
        - '#9ECE58'
        - '#FAED70'
        - '#396FE2'
        - '#BB80B3'
        - '#2DDAFD'
        - '#d0d0d0'
        - rgba(255, 255, 255, 0.2)
        - '#FF5370'
        - '#C3E88D'
        - '#FFCB6B'
        - '#82AAFF'
        - '#C792EA'
        - '#89DDFF'
        - '#ffffff'
  altIsMeta: true
  showBuiltinProfiles: false
  showRecentProfiles: 0
  background: colorScheme
hotkeys:
  profile: {}
  shell: {}
  toggle-window: []
  copy: []
  paste:
    - - Alt-Shift-V
  home: []
  end: []
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-next-word: []
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  new-tab: []
  ctrl-c: []
  search: []
  pane-focus-all: []
  serial: []
  settings: []
  ssh: []
  new-window: []
  toggle-fullscreen: []
  rename-tab: []
  close-tab: []
  reopen-tab: []
  next-tab: []
  previous-tab: []
  move-tab-left: []
  move-tab-right: []
  tab-1: []
  tab-2: []
  tab-3: []
  tab-4: []
  tab-5: []
  tab-6: []
  tab-7: []
  tab-8: []
  tab-9: []
  tab-10: []
  split-right: []
  split-bottom: []
  pane-maximize: []
  pane-nav-up: []
  pane-nav-down: []
  pane-nav-left: []
  pane-nav-right: []
  copy-current-path: []
  select-all: []
  clear: []
  telnet-profile-selector: []
  restart-telnet-session: []
  ssh-profile-selector: []
  restart-ssh-session: []
  launch-winscp: []
  restart-serial-session: []
  toggle-last-tab: []
  rearrange-panes: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-left: []
  split-top: []
  pane-nav-previous: []
  pane-nav-next: []
  close-pane: []
  switch-profile: []
  profile-selector: []
  profile-selectors: {}
serial: {}
ssh: {}
appearance:
  theme: Compact
  vibrancyType: blur
  opacity: 0.74
  css: >-
    /* * { color: blue !important; } */

    .xterm-screen, .xterm-text-layer, .xterm-selection-layer, .xterm-link-layer,
    .xterm-cursor-layer {
      width: 100% !important;
      // height: 100% !important;
    }
enableWelcomeTab: false
pluginBlacklist:
  - community-color-schemes
  - serial
  - ssh
  - telnet
  - theme-windows10
version: 3
profiles:
  - type: local
    name: PowerShell
    icon: >-
      <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true"
      class="svg-inline--fa fa-terminal fa-w-20 fa-2x" data-icon="terminal"
      data-prefix="fas" focusable="false" role="img" viewBox="0 0 640 512"><path
      fill="#0ff" stroke="none" stroke-width="1" d="M257.981 272.971L63.638
      467.314c-9.373 9.373-24.569 9.373-33.941 0L7.029
      444.647c-9.357-9.357-9.375-24.522-.04-33.901L161.011 256 6.99
      101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373
      24.569-9.373 33.941 0L257.981 239.03c9.373 9.372 9.373 24.568 0
      33.941zM640 456v-32c0-13.255-10.745-24-24-24H312c-13.255 0-24 10.745-24
      24v32c0 13.255 10.745 24 24 24h304c13.255 0 24-10.745
      24-24z"></path></svg>
    options:
      command: powershell.exe
      args:
        - '-nologo'
      env:
        TERM: cygwin
    id: local:custom:PowerShell:bd110e9c-a3ba-4e5c-b6fc-6897c15bba14
    group: Windows
  - type: local
    name: Ubuntu-18.04
    options:
      command: C:\WINDOWS\system32\wsl.exe
      args:
        - '-d'
        - Ubuntu-18.04
      env:
        TERM: xterm-color
        COLORTERM: truecolor
      cwd: //wsl$/Ubuntu-20.04/home/anoriqq
    group: WSL
    icon: >-
      <svg xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid"
      version="1.1" viewBox="0 0 256 256"><g><path fill="#DD4814"
      d="M255.637396,127.683191 C255.637396,198.196551 198.47207,255.363378
      127.954205,255.363378 C57.4348387,255.363378 0.27026393,198.196551
      0.27026393,127.683191 C0.27026393,57.1653255 57.4355894,0 127.954205,0
      C198.472821,0 255.637396,57.1653255 255.637396,127.683191
      L255.637396,127.683191 Z"></path><path fill="#FFF"
      d="M41.1334194,110.63254 C31.7139707,110.63254 24.0827683,118.264493
      24.0827683,127.683191 C24.0827683,137.097384 31.7139707,144.728587
      41.1334194,144.728587 C50.5476129,144.728587 58.1788152,137.097384
      58.1788152,127.683191 C58.1788152,118.264493 50.5476129,110.63254
      41.1334194,110.63254 L41.1334194,110.63254 Z M162.848282,188.111202
      C154.694569,192.820551 151.898839,203.240727 156.608938,211.389935
      C161.313032,219.543648 171.733208,222.338628 179.886921,217.629279
      C188.039883,212.925185 190.835613,202.505009 186.126264,194.350545
      C181.42217,186.202088 170.995988,183.407109 162.848282,188.111202
      L162.848282,188.111202 Z M78.1618299,127.683191 C78.1618299,110.836739
      86.5295015,95.9534545 99.3332551,86.9409032 L86.8703343,66.0667683
      C71.9555191,76.0365044 60.8581818,91.271132 56.2464282,109.113806
      C61.6276833,113.504845 65.0720469,120.189372 65.0720469,127.68244
      C65.0720469,135.171003 61.6276833,141.855531 56.2464282,146.246569
      C60.852176,164.094499 71.9495132,179.329877 86.8703343,189.299613
      L99.3332551,168.420223 C86.5295015,159.412927 78.1618299,144.530393
      78.1618299,127.683191 L78.1618299,127.683191 Z M127.954205,77.8855601
      C153.967109,77.8855601 175.30895,97.8302874 177.549138,123.265877
      L201.839859,122.907777 C200.644692,104.129689 192.441431,87.2719765
      179.836622,74.875871 C173.354792,77.3247625 165.86773,76.9501466
      159.396411,73.2197537 C152.91383,69.4788504 148.849361,63.1681877
      147.738276,56.3177478 C141.438123,54.5790499 134.807648,53.6271202
      127.952704,53.6271202 C116.168446,53.6271202 105.026815,56.3950733
      95.1344047,61.2913548 L106.979472,82.5175836 C113.351695,79.5521877
      120.460387,77.8855601 127.954205,77.8855601 L127.954205,77.8855601 Z
      M127.954205,177.475566 C120.460387,177.475566 113.351695,175.808188
      106.980223,172.843543 L95.1351554,194.069021 C105.027566,198.971308
      116.169196,201.740012 127.954205,201.740012 C134.80915,201.740012
      141.439625,200.787331 147.739026,199.043378 C148.850111,192.192938
      152.916082,185.888282 159.397161,182.140622 C165.872985,178.404223
      173.355543,178.036364 179.837372,180.485255 C192.442182,168.08915
      200.645443,151.231437 201.84061,132.453349 L177.543883,132.095249
      C175.30895,157.537595 153.967859,177.475566 127.954205,177.475566
      L127.954205,177.475566 Z M162.842276,67.2446686 C170.995988,71.9532669
      181.416915,69.1642933 186.121009,61.0105806 C190.830358,52.856868
      188.041384,42.4359413 179.886921,37.7258416 C171.733208,33.0217478
      161.313032,35.8167273 156.602182,43.9704399 C151.898839,52.1196481
      154.693818,62.5405748 162.842276,67.2446686 L162.842276,67.2446686
      Z"></path></g></svg>
    id: local:custom:WSL-Ubuntu-18.04:2c9c8c30-0fec-4833-a36d-5b7852eaecff
  - type: local
    name: Ubuntu-20.04
    options:
      command: C:\WINDOWS\system32\wsl.exe
      args:
        - '-d'
        - Ubuntu-20.04
      env:
        TERM: xterm-color
        COLORTERM: truecolor
      cwd: //wsl$/Ubuntu-20.04/home/anoriqq
    group: WSL
    id: local:custom:WSL-Ubuntu-18.04-copy:6be06603-6eb1-4a77-af27-60f83a502072
    icon: >-
      <svg xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid"
      version="1.1" viewBox="0 0 256 256"><g><path fill="#DD4814"
      d="M255.637396,127.683191 C255.637396,198.196551 198.47207,255.363378
      127.954205,255.363378 C57.4348387,255.363378 0.27026393,198.196551
      0.27026393,127.683191 C0.27026393,57.1653255 57.4355894,0 127.954205,0
      C198.472821,0 255.637396,57.1653255 255.637396,127.683191
      L255.637396,127.683191 Z"></path><path fill="#FFF"
      d="M41.1334194,110.63254 C31.7139707,110.63254 24.0827683,118.264493
      24.0827683,127.683191 C24.0827683,137.097384 31.7139707,144.728587
      41.1334194,144.728587 C50.5476129,144.728587 58.1788152,137.097384
      58.1788152,127.683191 C58.1788152,118.264493 50.5476129,110.63254
      41.1334194,110.63254 L41.1334194,110.63254 Z M162.848282,188.111202
      C154.694569,192.820551 151.898839,203.240727 156.608938,211.389935
      C161.313032,219.543648 171.733208,222.338628 179.886921,217.629279
      C188.039883,212.925185 190.835613,202.505009 186.126264,194.350545
      C181.42217,186.202088 170.995988,183.407109 162.848282,188.111202
      L162.848282,188.111202 Z M78.1618299,127.683191 C78.1618299,110.836739
      86.5295015,95.9534545 99.3332551,86.9409032 L86.8703343,66.0667683
      C71.9555191,76.0365044 60.8581818,91.271132 56.2464282,109.113806
      C61.6276833,113.504845 65.0720469,120.189372 65.0720469,127.68244
      C65.0720469,135.171003 61.6276833,141.855531 56.2464282,146.246569
      C60.852176,164.094499 71.9495132,179.329877 86.8703343,189.299613
      L99.3332551,168.420223 C86.5295015,159.412927 78.1618299,144.530393
      78.1618299,127.683191 L78.1618299,127.683191 Z M127.954205,77.8855601
      C153.967109,77.8855601 175.30895,97.8302874 177.549138,123.265877
      L201.839859,122.907777 C200.644692,104.129689 192.441431,87.2719765
      179.836622,74.875871 C173.354792,77.3247625 165.86773,76.9501466
      159.396411,73.2197537 C152.91383,69.4788504 148.849361,63.1681877
      147.738276,56.3177478 C141.438123,54.5790499 134.807648,53.6271202
      127.952704,53.6271202 C116.168446,53.6271202 105.026815,56.3950733
      95.1344047,61.2913548 L106.979472,82.5175836 C113.351695,79.5521877
      120.460387,77.8855601 127.954205,77.8855601 L127.954205,77.8855601 Z
      M127.954205,177.475566 C120.460387,177.475566 113.351695,175.808188
      106.980223,172.843543 L95.1351554,194.069021 C105.027566,198.971308
      116.169196,201.740012 127.954205,201.740012 C134.80915,201.740012
      141.439625,200.787331 147.739026,199.043378 C148.850111,192.192938
      152.916082,185.888282 159.397161,182.140622 C165.872985,178.404223
      173.355543,178.036364 179.837372,180.485255 C192.442182,168.08915
      200.645443,151.231437 201.84061,132.453349 L177.543883,132.095249
      C175.30895,157.537595 153.967859,177.475566 127.954205,177.475566
      L127.954205,177.475566 Z M162.842276,67.2446686 C170.995988,71.9532669
      181.416915,69.1642933 186.121009,61.0105806 C190.830358,52.856868
      188.041384,42.4359413 179.886921,37.7258416 C171.733208,33.0217478
      161.313032,35.8167273 156.602182,43.9704399 C151.898839,52.1196481
      154.693818,62.5405748 162.842276,67.2446686 L162.842276,67.2446686
      Z"></path></g></svg>
recoverTabs: false
configSync:
  parts: {}
profileDefaults: {}
```

</details>
