### ISSUE TITLE
Handshake failed: signature verification failed

### ISSUE THREAD

**Issue by DehanLUO** [Eugeny/tabby#5120]
zsh, MacOS Termianl
`ssh admin@172.16.176.181 -p 2122` works with the following config at ~/.ssh/config
```
#device
Host 172.16.176.181
  HostName 172.16.176.181
  KexAlgorithms +diffie-hellman-group1-sha1
  HostKeyAlgorithms +ssh-dss
```

However, with the following config in Tabby(1.0.167)
```
profiles:
  - type: ssh
    name: 172.16.176.181
    icon: fas fa-desktop
    options:
      host: 172.16.176.181
      port: 2122
      user: admin
      algorithms:
        hmac: []
        kex:
          - diffie-hellman-group1-sha1
        cipher: []
        serverHostKey:
          - ssh-dss
      privateKeys: []
      forwardedPorts: []
      scripts: []
```
I always get following errors when I get access to my device
```
 SSH  Connecting to 172.16.176.181
 SSH  Host key fingerprint:
 SSH   SHA256  79e16d2f89af484cf0b80bea48276939804e3942b7358297f5d113e005ce8101 
 X  Handshake failed: signature verification failed
```

**Comment by Eugeny** [comment]
This likely due to _no_ algorithms being selected for message authentication and encryption - try with a clean profile created from the UI + the `diffie-hellman-group1-sha1` kex.

**Comment by DehanLUO** [comment]
Thanks for your help.

I reinstalled the tabby and cleared the cache
```
brew reinstall tabby
rm -rf /System/Volumes/Data/Users/dehan/Library/Application Support/tabby/
```
I added `diffie-hellman-group1-sha` and `ssh-dss` from the UI. 
However, the same error occurs again.
```
version: 3
profiles:
  - type: ssh
    name: 172.16.177.156
    icon: fas fa-desktop
    options:
      host: 172.16.177.156
      port: 2122
      user: admin
      algorithms:
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group1-sha1
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-dss
          - ssh-ed25519
          - ssh-rsa
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    id: ssh:custom:172.16.177.156:a8a194f2-c3db-4190-9172-d21dde76eaa2
hotkeys:
  toggle-window:
    - Ctrl-Space
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-window:
    - ⌘-N
  new-tab:
    - ⌘-T
  profile: {}
  profile-selectors: {}
  toggle-fullscreen:
    - Ctrl+⌘+F
  close-tab:
    - ⌘-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - Ctrl-Tab
  previous-tab:
    - Ctrl-Shift-Tab
  move-tab-left:
    - ⌘-Shift-Left
  move-tab-right:
    - ⌘-Shift-Right
  rearrange-panes:
    - ⌘-Shift
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3:
    - ⌘-3
  tab-4:
    - ⌘-4
  tab-5:
    - ⌘-5
  tab-6:
    - ⌘-6
  tab-7:
    - ⌘-7
  tab-8:
    - ⌘-8
  tab-9:
    - ⌘-9
  tab-10:
    - ⌘-0
  duplicate-tab: []
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-Shift-D
  split-bottom:
    - ⌘-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-Shift-W
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
terminal:
  searchOptions: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    selection: null
    cursor: '#FFCC00'
    cursorAccent: null
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
ssh: {}
configSync:
  parts: {}
clickableLinks: {}
appearance: {}
pluginBlacklist: []
enableWelcomeTab: false
profileDefaults: {}
```

btw, I found some logs in the cache library.
- /System/Volumes/Data/Users/dehan/Library/Application Support/tabby/Local Storage/leveldb/000003.log
[000003.log](https://github.com/Eugeny/tabby/files/7698050/000003.log)
- /System/Volumes/Data/Users/dehan/Library/Application Support/tabby/log.txt
[log.txt](https://github.com/Eugeny/tabby/files/7698051/log.txt)
and the config
