### ISSUE TITLE
When maximizing a terminal the split pane divider lines still visible.

### ISSUE THREAD

**Issue by jonnyhoff** [Eugeny/tabby#5244]
**Describe the problem**:
When maximizing a terminal the split pane divider lines still visible.

![tabby_split](https://user-images.githubusercontent.com/8642945/146923370-78927d40-369b-45da-bba0-d3bc745737b9.png)

**To Reproduce**:
Split terminal into multiple terminals
Maximize a terminal

OS: Fedora 35
Tabby: 1.0.168

**Comment by Eugeny** [comment]
You can set an opaque background for maximized panes with this custom CSS:

```css
split-tab > .child.maximized {
    background: black !important;
}
```
