### ISSUE TITLE
Windows: hotkeys Ctrl-Alt-Up/Down/Left/Right not work

### ISSUE THREAD

**Issue by Alex-duzhichao** [Eugeny/tabby#5454]
```yaml
pane-nav-down:
  - Ctrl-Alt-J
  - Ctrl-Alt-Down
  - Alt-Down
  pane-nav-left:
  - Ctrl-Alt-H
  - Ctrl-Alt-Left
  - Alt-Left
  pane-nav-right:
  - Ctrl-Alt-L
  - Ctrl-Alt-Right
  - Alt-Right
  pane-nav-up:
  - Ctrl-Alt-K
  - Ctrl-Alt-Up
  - Alt-Up
```
The above snippet is my hotkey config in config.yaml. I configure `pane-nav-*`  functions with three different kind hotkeys:
1. `Ctrl-Alt-H/J/K/L`
2. `Ctrl-Alt-Up/Down/Left/Right`
3. `Alt-Up/Down/Left/Right`

`Kind 1` and `kind 3` work fine in my windows PC, but when i press keys of `kind 2`, nothing happens in Tabby. It seems like something is wrong when `Ctrl`, `Alt`, `Up/Down/Left/Right` are combined together.

I have checked console output in DevTools, but unfortunately nothing was been outputted.
