### ISSUE TITLE
More visible display of active tabs

### ISSUE THREAD

**Issue by timnick-snow** [Eugeny/tabby#5945]
![image](https://user-images.githubusercontent.com/33312542/158532819-76a8a691-cf21-40e4-9a88-448020fe29c2.png)

The currently working window, its tabs should be more visible.

 For example, use another background color that is easier to distinguish

**Comment by ix-seb** [comment]
+1

I use Custom CSS (at the bottom of Appearance setting tab) with this values:
```css
app-root>.content .tab-bar>.tabs tab-header.active
{
    background: rgba(39,49,60,0.99);
    font-weight:600;
}
app-root>.content .tab-bar>.tabs tab-header { color: #999}
```

For me it's better.
