### ISSUE TITLE
altIsMeta not work on macOS

### ISSUE THREAD

**Issue by JianYiheng** [Eugeny/tabby#6029]
**Describe the problem**:
Platform: macOS Monterey 12.3
``Use ⌥ as the Meta key`` does not work on Mac OS. When I press ``option+n``, ``˜`` is typed out. This troubles me when I use ``zellij``, which uses ``option+n`` to create new tab.

``Use ⌥ as the Meta key`` works well on macOS default terminal app. A new tab is created when I press ``option+n``.

My config file is listed below:
```
terminal:
  searchOptions: {}
  colorScheme:
    name: Material
    foreground: '#eceff1'
    background: rgba(38, 50, 56, 1)
    selection: null
    cursor: '#FFCC00'
    cursorAccent: null
    colors:
      - '#000000'
      - '#D62341'
      - '#9ECE58'
      - '#FAED70'
      - '#396FE2'
      - '#BB80B3'
      - '#2DDAFD'
      - '#d0d0d0'
      - rgba(255, 255, 255, 0.2)
      - '#FF5370'
      - '#C3E88D'
      - '#FFCB6B'
      - '#82AAFF'
      - '#C792EA'
      - '#89DDFF'
      - '#ffffff'
  customColorSchemes: []
  pasteOnMiddleClick: false
  font: JetBrainsMono Nerd Font
  copyOnSelect: true
  altIsMeta: true
```

**To Reproduce**:
1. select ``Use ⌥ as the Meta key`` in Tabby settings
2. open a new terminal
3. install ``zellij`` by ``brew install zellij``
4. create a zellij session by ``zellij``
5. press ``option + n`` and check if a new tab is created. (In my case, ``˜`` is typed out)
