### ISSUE TITLE
change background picture?

### ISSUE THREAD

**Issue by kikyoulg** [Eugeny/tabby#6138]
maybe someday

**Comment by bear2529** [comment]
body > app-root > div > div.content > tab-body.content-tab.ng-tns-c0-0.ng-star-inserted.content-tab-active.active > split-tab > ssh-tab::before{
content:"";
      /*-webkit-filter: opacity(50%);  
      filter: opacity(50%); */
      background-image:url('C:\\Users\\bear\\Pictures\\壁纸\\26.jpg');//图片的链接，本地的或者网络上的位置都可以
background-repeat: no-repeat;
      opacity:0.2;//透明度设置
      z-index:-1;
      background-size:100%;
      width:100%; 
      height:100%;
      position:absolute;
      top:0px;
      left:0px;
}

**Comment by gflujan** [comment]
@kikyoulg 
This is what I use to alter the background image in Tabby. You can tweak the settings as needed. 

```css
.xterm-viewport {
   background-image: url("/path/to/your/image/here");
   background-repeat: no-repeat;
   background-position: 45%;
   background-size: auto 100vh;
   filter: opacity(50%);
   opacity: 0.2;
   z-index: 1;
}
```
