### ISSUE TITLE
Make clickable links handlers enabled or disabled with custom modifier 

### ISSUE THREAD

**Issue by najib-houcine** [Eugeny/tabby#6222]
**Is your feature request related to a problem? Please describe.**
There is no way to disable or enable certain links handlers , all enabled by default.

**Describe the solution you'd like**
Configuration like below
```yml
clickableLinks:
# Global modifer for all handlers
  modifier:  null
  urlhanler:
    enabled: true
    modifier:  ctrlKey
  unixfilehanler:
    enabled: false
    modifier: metaKey
  .
  .
  .
```

**Describe alternatives you've considered**
Like the above

**Additional context**
