### ISSUE TITLE
Error: openpty failed

### ISSUE THREAD

**Issue by ChivialK** [Eugeny/tabby#7853]
Shows nothing when opening new tab, and the develop console shows
`Unhandled exception: Error: openpty failed.`

[Images](https://imgur.com/a/yfoyQjC)

Also tried to add these in config from related issues (https://github.com/Eugeny/tabby/issues/5789), but seems only works on windows.
```
terminal:
  environment: {}
  useConPTY: false
  ...
```

Version: 1.0.188 & 1.0.189(nightly build)
Platform: macOS x64 22.2.0
OS: Ventura 13.1
Plugins: none
Frontend: xterm-webgl
