### ISSUE TITLE
highlight current select tab

### ISSUE THREAD

**Issue by vesio** [Eugeny/tabby#8133]
**Is your feature request related to a problem? Please describe.**
I can't find current working tab.
I think there maybe  a config to highlight current tab

**Describe the solution you'd like**
Before
![企业微信截图_16795526164768](https://user-images.githubusercontent.com/24934917/227120801-de8e69b4-2ae0-4cef-b107-6b00ca0c4629.png)
After
![企业微信截图_16795523778239](https://user-images.githubusercontent.com/24934917/227120735-96de3f51-dd00-4266-8c61-ca5826c5760d.png)

There is a orange line

**Additional context**
``` css
#cdk-drop-list-0 > tab-header.ng-tns-c127-0.fully-draggable.ng-trigger.ng-trigger-animateTab.ng-star-inserted.active:after {
    content: "";
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    pointer-events: none;
background:#ff6c37;
    border-top: 2px solid var(--base-color-brand);
    height: 3px;
}
```

t or screenshots about the feature request here.
