### ISSUE TITLE
-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by NetRat88** [Eugeny/tabby#9609]
**Describe the problem**:
When I connect to one of my Raspberry Pi's using Tabby zsh Terminal I got the following warning:

-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

It seems that the Tabby terminal tries to change the locale environment on my pi isn't it? How can I avoid this warning message?
My raspberry pi's locale environement is set to GB instead of US:

pi@raspberrypi:~ $ cat /etc/default/locale
#  File generated by update-locale
LANG=en_GB.UTF-8

I don't receive the warning if I connect from my mac terminal or visual studio terminal.

**To Reproduce**:
1. Set locale environement variable on an SSH host to LANG=en_GB.UTF-8
2. Start a Tabby Terminal and connect to ssh user@IP-host

**Comment by seraphyn** [comment]
That's always buggy

```
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
-bash: Warnung: setlocale: LC_COLLATE: Kann die Regionseinstellungen nicht ändern (en_US.UTF-8): Datei oder Verzeichnis nicht gefunden
-bash: Warnung: setlocale: LC_COLLATE: Kann die Regionseinstellungen nicht ändern (en_US.UTF-8): Datei oder Verzeichnis nicht gefunden
-bash: Warnung: setlocale: LC_COLLATE: Kann die Regionseinstellungen nicht ändern (en_US.UTF-8): Datei oder Verzeichnis nicht gefunden
-bash: Warnung: setlocale: LC_COLLATE: Kann die Regionseinstellungen nicht ändern (en_US.UTF-8): Datei oder Verzeichnis nicht gefunden
ME@SERVER ~$ locale -a
C
C.utf8
POSIX
de_DE.utf8
```

**Comment by seraphyn** [comment]
@NetRat88 

User this ansible playbook from me:
```
---
- name: "add en_US.UTF-8 hinzu, do not deleter standard"
  hosts: debian
  become: yes
  tasks:
    - name: "locale here, for shure"
      apt:
        name: locales
        state: present
        update_cache: yes

    - name: "Activate en_US.UTF-8 in /etc/locale.gen"
      lineinfile:
        path: /etc/locale.gen
        regexp: "^#?\\s*en_US.UTF-8"
        line: "en_US.UTF-8 UTF-8"
        state: present

    - name: "generate locale"
      command: "locale-gen"
      register: locale_gen_result
      changed_when: "'Generating locales' in locale_gen_result.stdout"
```

Should fix this on many Servers
