### ISSUE TITLE
double colon (::) makes terminal text distorted

### ISSUE THREAD

**Issue by nullaegy** [Eugeny/tabby#9848]
Version: 1.0.211
Platform: Windows x64 10.0.22621
Plugins: none
Frontend: xterm-webgl

This behaviour has been there several version before, I just recently figured out how to reproduce a higher probability.

**To Reproduce**:

If you type anything to a linux terminal which contains :: for example:
`echo "something::other"` the terminal switch to distorted view and if you go back even the previously good text are looking distorted as well.
Until you press F11 (fullscreen) and back.

sometimes you have to trigger the behaviour:
`grep -a :: /var/log/ -rni`
and after that the glitch is there again.

![image](https://github.com/user-attachments/assets/2d9b07fc-cb7c-40eb-b5ca-b5ec2a1ddf5e)

**tabby config**
```
appearance:
  vibrancyType: fluent
  tabsLocation: left
  dockHideOnBlur: true
  dockFill: 0.63
  dockAlwaysOnTop: false
  dockScreen: 917481049
  theme: Standard (legacy)
  spaciness: 0.9
  flexTabs: true
enableWelcomeTab: false
clickableLinks:
  modifier: altKey
hacks: {}
pluginBlacklist:
  - fit-screen
```
```
language: en-US
lectronFlags:
  - - force_discrete_gpu
    - '0'
electronFlags:
  - - force_discrete_gpu
    - '0'
accessibility:
  animations: false
```
